### Загрузка библиотек

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pickle # Библиотека для сохранения моделей

### Создание синтетических данных

In [2]:
salary = [50,55,60,70,120,250,50,30,100,300,50,75]
experience = [1,2,3,20,1,2,8,9,3,6,7,9]

In [3]:
print(f'salary: {len(salary)} experience: {len(experience)}')

salary: 12 experience: 12


In [4]:
# Разделение выборки на обучающую и проверочную
X = np.array(experience).reshape(-1, 1)
y = np.array(salary)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.2,
                                                    shuffle = True,
                                                    random_state = 42)

### Линейная регрессия

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [6]:
print(y_pred)

[ 87.3173516   91.3413242  111.46118721]


In [7]:
print(y_test)

[ 50 300  50]


### Сохранение модели

In [8]:
pickle.dump(lr, open('lr_model.pkl', 'wb'))

In [9]:
loaded_model = pickle.load(open('lr_model.pkl', 'rb'))
loaded_model.predict(X_test)

array([ 87.3173516 ,  91.3413242 , 111.46118721])