### Решение регрессионной задачи с помощью нейронной сети

In [1]:
import torch
from torch.autograd import Variable

import matplotlib.pyplot as plt
from IPython.display import IFrame
%matplotlib inline

import numpy as np
import pandas as pd
import imageio

In [2]:
torch.manual_seed(42)
# Генерации 100 чисел с равномерным распределением
torch.rand(100)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
        0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090,
        0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890,
        0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103,
        0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542,
        0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
        0.9811, 0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418,
        0.1591, 0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524,
        0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313, 0.3227,
        0.0162])

In [3]:
# Сортировка последовательности
torch.sort(torch.rand(100))[0]

tensor([0.0029, 0.0293, 0.0337, 0.0594, 0.0600, 0.0624, 0.0758, 0.0766, 0.0850,
        0.0897, 0.1035, 0.1054, 0.1258, 0.1265, 0.1330, 0.1330, 0.1371, 0.1568,
        0.1585, 0.1612, 0.1716, 0.1816, 0.2007, 0.2083, 0.2137, 0.2147, 0.2234,
        0.2247, 0.2297, 0.2469, 0.2709, 0.2846, 0.2849, 0.3083, 0.3139, 0.3219,
        0.3288, 0.3289, 0.3336, 0.3510, 0.3624, 0.3676, 0.3722, 0.3881, 0.3908,
        0.4008, 0.4117, 0.4121, 0.4137, 0.4250, 0.4340, 0.4452, 0.4505, 0.4654,
        0.4701, 0.4761, 0.5014, 0.5073, 0.5117, 0.5535, 0.5643, 0.5782, 0.5907,
        0.5944, 0.6044, 0.6099, 0.6115, 0.6161, 0.6202, 0.6249, 0.6258, 0.6401,
        0.6431, 0.6541, 0.6558, 0.6625, 0.6757, 0.6783, 0.6870, 0.6947, 0.7099,
        0.7581, 0.7583, 0.7610, 0.7628, 0.7672, 0.7792, 0.8196, 0.8460, 0.8712,
        0.8870, 0.9037, 0.9192, 0.9295, 0.9297, 0.9302, 0.9545, 0.9554, 0.9555,
        0.9998])

In [4]:
x = torch.unsqueeze(torch.sort(torch.rand(100))[0], dim = 1)
print(x)

tensor([[0.0023],
        [0.0026],
        [0.0036],
        [0.0065],
        [0.0134],
        [0.0240],
        [0.0248],
        [0.0323],
        [0.0459],
        [0.0485],
        [0.0521],
        [0.0580],
        [0.0716],
        [0.0825],
        [0.0892],
        [0.0939],
        [0.1165],
        [0.1197],
        [0.1332],
        [0.1481],
        [0.1514],
        [0.1519],
        [0.1733],
        [0.1764],
        [0.1786],
        [0.1941],
        [0.1985],
        [0.1993],
        [0.2003],
        [0.2122],
        [0.2255],
        [0.2539],
        [0.2545],
        [0.2576],
        [0.2636],
        [0.2726],
        [0.2956],
        [0.2959],
        [0.3096],
        [0.3155],
        [0.3335],
        [0.3370],
        [0.3382],
        [0.3396],
        [0.3413],
        [0.3470],
        [0.3514],
        [0.3705],
        [0.3821],
        [0.3849],
        [0.3865],
        [0.3994],
        [0.3998],
        [0.4089],
        [0.4118],
        [0

In [5]:
y_true = 2*x
y = y_true + (torch.rand(x.size()) - 0.5) # Добавляем шум
print(y)

tensor([[ 0.0208],
        [-0.1009],
        [-0.1649],
        [-0.2263],
        [-0.3801],
        [ 0.4673],
        [-0.1504],
        [ 0.1971],
        [-0.0817],
        [ 0.1376],
        [ 0.5704],
        [ 0.3464],
        [-0.2901],
        [ 0.3635],
        [ 0.6530],
        [ 0.3194],
        [ 0.5682],
        [ 0.7324],
        [ 0.1898],
        [ 0.3999],
        [-0.0448],
        [ 0.2008],
        [ 0.7169],
        [ 0.6091],
        [ 0.0407],
        [-0.0127],
        [ 0.0554],
        [-0.0948],
        [ 0.0147],
        [ 0.3008],
        [ 0.7884],
        [ 0.5915],
        [ 0.1287],
        [ 0.1141],
        [ 0.7760],
        [ 0.1734],
        [ 0.5297],
        [ 0.8317],
        [ 0.3877],
        [ 0.5764],
        [ 0.6235],
        [ 0.5557],
        [ 0.4230],
        [ 0.2335],
        [ 0.2784],
        [ 0.4263],
        [ 1.1857],
        [ 0.4995],
        [ 0.4284],
        [ 0.8910],
        [ 0.9108],
        [ 1.0727],
        [ 1.

In [6]:
x, y = Variable(x), Variable(y)

In [7]:
x_plot = x.data.numpy()
y_plot = y.data.numpy()

In [8]:
class LinearNet(torch.nn.Module):
    def __init__(self, n_feature, n_output, use_bias = False):
        super(LinearNet, self).__init__()
        self.output = torch.nn.Linear(n_feature, n_output, bias = use_bias)
        
    def forward(self, x):
        x = self.output(x)
        return x            

In [9]:
net = LinearNet(n_feature = 1, n_output = 1)
print(net)

LinearNet(
  (output): Linear(in_features=1, out_features=1, bias=False)
)


In [10]:
# Определяем функцию потерь
loss_func = torch.nn.MSELoss()

In [11]:
prediction = net(x)
loss = loss_func(prediction, y)

In [12]:
prediction - y

tensor([[-0.0214],
        [ 0.1001],
        [ 0.1639],
        [ 0.2245],
        [ 0.3763],
        [-0.4740],
        [ 0.1434],
        [-0.2062],
        [ 0.0689],
        [-0.1511],
        [-0.5850],
        [-0.3627],
        [ 0.2700],
        [-0.3866],
        [-0.6779],
        [-0.3456],
        [-0.6007],
        [-0.7659],
        [-0.2271],
        [-0.4414],
        [ 0.0024],
        [-0.2433],
        [-0.7654],
        [-0.6584],
        [-0.0907],
        [-0.0416],
        [-0.1110],
        [ 0.0390],
        [-0.0708],
        [-0.3602],
        [-0.8515],
        [-0.6625],
        [-0.1999],
        [-0.1862],
        [-0.8497],
        [-0.2497],
        [-0.6124],
        [-0.9145],
        [-0.4743],
        [-0.6647],
        [-0.7168],
        [-0.6500],
        [-0.5176],
        [-0.3285],
        [-0.3738],
        [-0.5234],
        [-1.2840],
        [-0.6032],
        [-0.5353],
        [-0.9987],
        [-1.0190],
        [-1.1844],
        [-1.

In [13]:
E = pd.DataFrame((prediction - y).detach().numpy())

In [14]:
print(E)

           0
0  -0.021413
1   0.100134
2   0.163855
3   0.224516
4   0.376301
..       ...
95 -1.818147
96 -1.693967
97 -2.264475
98 -2.366048
99 -2.011724

[100 rows x 1 columns]


In [15]:
# Среднее значение квадрата ошибки
print(loss)

tensor(1.4986, grad_fn=<MseLossBackward0>)


In [16]:
torch.mean((prediction - y)*(prediction - y))

tensor(1.4986, grad_fn=<MeanBackward0>)

In [ ]:
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)
fig, ax = plt.subplots()
ax.plot(t, s)
ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
plt.show()