### Использование библиоткеи NumPy - Часть I
https://www.youtube.com/watch?v=iwKolVZLApI

In [1]:
import numpy as np

In [2]:
# Создание простого одномерного массива
a=np.array([1,2,3,4], dtype=np.float32)

In [3]:
a, a.dtype # Сам массив + тип элементов, которые хранятся в массиве

(array([1., 2., 3., 4.], dtype=float32), dtype('float32'))

#### Типы данных
- np.int32
- np.int64
- np.float32
- np.float64
- np.complex
- np.bool

**Преобразование типов на лету:**  
Старый формат
```python
a.astype(np.complex)
```
Новый формат  
```python
a.astype(complex)
```

In [4]:
a.astype(complex), a.astype(np.double)

(array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]), array([1., 2., 3., 4.]))

In [5]:
# Индексация элементов массива
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
b[len(b)-1], b[-1] # Обращаемся к последнему элементу массива

(14, 14)

In [7]:
# Первые 5 элементов
b[:5], b[0:5], b[0:5:1] # Для последнего примера: начало, конец, шаг

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [8]:
b[slice(0,5,1)] # Срез с помощью slice

array([0, 1, 2, 3, 4])

In [9]:
# Вывод элементов с шагом 2
b[::2], b[0::2]

(array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14]))

В массиве случайных чисел найти все числа кратные 5

In [10]:
c=np.random.randint(0,100,20)

In [11]:
c

array([77, 67, 94, 88,  3, 25, 87, 35, 94, 16, 45, 26, 24, 45, 84, 39, 29,
       40, 83, 21])

In [12]:
c[np.logical_not(c % 5)] # Использование фильтрации по булевской маске

array([25, 35, 45, 45, 40])

In [13]:
np.where(np.logical_not(c % 5)) # Позиции элементов, для которых маска совпала

(array([ 5,  7, 10, 13, 17], dtype=int64),)