### Использование библиоткеи NumPy - Часть IV
https://www.youtube.com/watch?v=WDe8puOOz4w

In [1]:
import numpy as np

In [2]:
a = np.zeros(shape=(3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
b = np.zeros_like(a) # Полная копия объекта и данных
a[0][1]=-0.1
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
e = np.ones(shape=(3,2))
e

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
ar_1 = np.arange(1, 10)
ar_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
ar_2 = np.arange(1, 10, 0.5) # Последняя точка не входи
ar_2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [9]:
# Последняя точка входит !!!
ar_3 = np.linspace(0, 1, 5, endpoint=True)
ar_3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 7 случайных чисел от 0 до 111
r = np.random.randint(0, 111, size=(7,))
r

array([80, 41, 61, 31, 93, 71, 19])

In [12]:
# Сравнение элементов с заданной точностью
a = np.random.random(size=(2,5))
b = a + np.random.random(size=(2,5)) * 1e-6

In [14]:
# Поэлементное сравнение
# rtol, atol - относительная и абсолютная погрешности
np.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [15]:
# Условие должно выполняться для всех элементов
np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)

False

In [16]:
# Найти решение задачи регрессии
X = np.array([[3, 4], [2, 7], [1, 5]])
y = np.array([1, 4, 2])
E = np.eye(2)
lam = 0.01
w = np.linalg.inv(X.T @ X + lam * E) @ X.T @ y
w

array([-0.43950792,  0.61798406])

In [17]:
np.random.seed(2048)
a = np.random.choice(10, size=(3, 10))
a

array([[5, 7, 5, 9, 8, 6, 1, 2, 7, 8],
       [6, 9, 2, 7, 6, 0, 3, 9, 2, 4],
       [9, 1, 8, 3, 5, 2, 1, 0, 5, 6]])

In [18]:
np.sort(a.ravel()) # ravel - преобразует массив в строку

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7,
       7, 8, 8, 8, 9, 9, 9, 9])